services:
  review-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    volumes:
      - local-state:/app/.local_state

volumes:
  local-state:
